### ISSUE TITLE
Outdated gulp version

### ISSUE THREAD

**Issue by bertob** [moklick/generator-leaflet#2]
I tried to scaffold a new project using this generator, but when running "gulp watch" after the setup I got this error:

```
[gulp] Warning: gulp version mismatch:
[gulp] Running gulp is 3.6.2
[gulp] Local gulp (installed in gulpfile dir) is 3.5.6
```

I tried updating the local gulp by running "npm install gulp@3.6.2 --save" but that didn't work either.
This is the error I got:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (PROJECT_PATH/node_modules/gulp-useref/index.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by moklick** [comment]
thanks! I will check that.

**Comment by moklick** [comment]
fixed.

I updated the dependencies, did some minor changes to the Gulpfile.

https://github.com/moklick/generator-leaflet/commit/930e7fc0d0d1397fedaa8a570fc95065bc5d7ba6
https://github.com/moklick/generator-leaflet/commit/b49b5009c4cc4b8fd33842c854e7a219900609c0

**Comment by bertob** [comment]
Thanks, gulp works without any problems now.
