### ISSUE TITLE
When I run npm run gulp I got an error with 'imagemin-jpegtran'

### ISSUE THREAD

**Issue by jeremyfourna** [moklick/generator-leaflet#4]
This is what I get when I run **npm run gulp**

[23:02:10] Using gulpfile ~/my-map-app/gulpfile.js
[23:02:10] Starting 'clean'...
[23:02:10] Finished 'clean' after 59 ms
[23:02:10] Starting 'default'...
[23:02:10] Starting 'styles'...
[23:02:10] Starting 'scripts'...
[23:02:10] Starting 'images'...
[23:02:10] 'images' errored after 66 ms
[23:02:10] Error: Cannot find module 'imagemin-jpegtran'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dexterneo/my-map-app/node_modules/gulp-imagemin/node_modules/imagemin/index.js:171:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dexterneo/my-map-app/node_modules/gulp-imagemin/index.js:8:16)
[23:02:10] Finished 'default' after 312 ms
[23:02:10] gulp-size: total 476 B
[23:02:10] Finished 'scripts' after 302 ms
[23:02:10] gulp-size: total 474 B
[23:02:10] Finished 'styles' after 386 ms
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

I already installed nodejs-legacy so the problem is elsewhere. When I run npm install, all the module install themselves correctly.

Can somebody help me with this error ?

**Comment by jeremyfourna** [comment]
When I remove all the install and run it again but without topojson It works so I close this issue

**Comment by moklick** [comment]
Hey @dexterneo!

Thanks for reporting an issue. I will check if I can reproduce this error.
Is there still a problem with the topojson support?
