### ISSUE TITLE
Unmet peer dependency yo@>=1.0.0

### ISSUE THREAD

**Issue by powpow12** [moklick/generator-leaflet#7]
Hello, 

ran into this issue today but I couldn't determine the missing dependency, 

```
rpowell@rpowell-laptop:/usr/local/lib/node_modules$ npm install -g generator-leaflet
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/home/rpowell/.nvm/versions/node/v5.9.1/lib
├── generator-leaflet@0.0.17 
└── UNMET PEER DEPENDENCY yo@>=1.0.0
```

I installed yo as global, here is the version number, 

```
rpowell@rpowell-laptop:~/Documents/projects$ npm list yo
/home/rpowell/Documents/projects
└── (empty)

npm ERR! code 1
rpowell@rpowell-laptop:~/Documents/projects$ npm list -g yo
/home/rpowell/.nvm/versions/node/v5.9.1/lib
└── yo@1.7.0 

```

While searching, I found this thread, but none of the suggested solutions worked for me https://github.com/yeoman/generator-angular/issues/1192. 

I decided to move ahead with running the generator, all seemed to be good until running gulp build (had to download both bower and gulp to run via command line).  

```
[11:24:20] Finished 'scripts' after 202 ms
[11:24:20] gulp-size: total 278 B
[11:24:20] Finished 'styles' after 338 ms
[11:24:20] Starting 'html'...
events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (gulp-useref: no such file or directory '/home/rpowell/Documents/projects/myarea_lookup/app/lib/styles/leaflet.css')
    at Transform.emit (events.js:157:17)
    at Transform.onerror (/home/rpowell/Documents/projects/myarea_lookup/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
```

Finally, when I run gulp watch, I get a blank app with a couple 404 errors for js and css, please see screenshot here http://snag.gy/fgHaa.jpg.

**Comment by moklick** [comment]
Thanks I will check that!
